import { Injectable } from '@angular/core';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface PDFGenerationData {
  smeName: string;
  generationDate: Date;
  investmentScore: {
    overall: number;
    recommendation: string;
    confidence: number;
    breakdown: {
      financial: number;
      market: number;
      team: number;
      traction: number;
    };
  };
  insights: Array<{
    title: string;
    description: string;
    type: string;
    severity: 'low' | 'medium' | 'high';
    recommendation: string;
    source?: string;
    confidence?: number;
  }>;
  marketContext?: string;
  processingTimeMs?: number;
}

@Injectable({
  providedIn: 'root',
})
export class AnalysisPdfService {
  /**
   * Generate branded PDF from analysis data
   */
  async generatePdf(data: PDFGenerationData): Promise<void> {
    try {
      console.log('📄 [PDF] Generating PDF report...');

      // Create HTML container
      const container = this.createPdfHtml(data);
      document.body.appendChild(container);

      // Convert to canvas
      const canvas = await html2canvas(container, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
      });

      // Create PDF
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const imgData = canvas.toDataURL('image/png');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const imgHeight = (canvas.height * pageWidth) / canvas.width;

      let yPosition = 0;

      // Add pages
      while (yPosition < imgHeight) {
        if (yPosition > 0) {
          pdf.addPage();
        }
        pdf.addImage(imgData, 'PNG', 0, -yPosition, pageWidth, imgHeight);
        yPosition += pageHeight;
      }

      // Download
      const fileName = `${data.smeName}-Analysis-${this.formatDateForFilename(
        data.generationDate
      )}.pdf`;
      pdf.save(fileName);

      console.log('✅ [PDF] PDF generated and downloaded:', fileName);

      // Cleanup
      document.body.removeChild(container);
    } catch (error) {
      console.error('❌ [PDF] Error generating PDF:', error);
      throw error;
    }
  }

  /**
   * Create HTML structure for PDF rendering
   */
  private createPdfHtml(data: PDFGenerationData): HTMLElement {
    const container = document.createElement('div');
    container.style.width = '210mm';
    container.style.padding = '20mm';
    container.style.fontFamily =
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
    container.style.lineHeight = '1.6';
    container.style.color = '#1e293b';
    container.style.backgroundColor = '#ffffff';

    // Header
    const header = document.createElement('div');
    header.style.borderBottom = '2px solid #0d9488';
    header.style.paddingBottom = '16px';
    header.style.marginBottom = '24px';

    const title = document.createElement('h1');
    title.textContent = `${data.smeName} Report`;
    title.style.margin = '0 0 8px 0';
    title.style.fontSize = '28px';
    title.style.fontWeight = '700';
    title.style.color = '#0f172a';

    const meta = document.createElement('div');
    meta.style.fontSize = '11px';
    meta.style.color = '#64748b';
    meta.style.display = 'flex';
    meta.style.justifyContent = 'space-between';
    meta.innerHTML = `
      <span>Generated: ${this.formatDateForDisplay(data.generationDate)}</span>
      <span>Kapify Platform</span>
    `;

    header.appendChild(title);
    header.appendChild(meta);
    container.appendChild(header);

    // Investment Score Card
    const scoreCard = this.createScoreCard(data.investmentScore);
    container.appendChild(scoreCard);

    // Market Context (if available)
    if (data.marketContext) {
      const marketSection = this.createMarketContextSection(data.marketContext);
      container.appendChild(marketSection);
    }

    // Insights Section
    const insightsSection = this.createInsightsSection(data.insights);
    container.appendChild(insightsSection);

    // Footer
    const footer = document.createElement('div');
    footer.style.marginTop = '32px';
    footer.style.paddingTop = '16px';
    footer.style.borderTop = '1px solid #e2e8f0';
    footer.style.fontSize = '10px';
    footer.style.color = '#94a3b8';
    footer.style.textAlign = 'center';
    footer.innerHTML = `
      <p style="margin: 0;">This analysis was generated by Kapify Decision Intelligence.</p>
      <p style="margin: 8px 0 0 0;">Processing time: ${
        data.processingTimeMs || 'N/A'
      }ms</p>
    `;
    container.appendChild(footer);

    return container;
  }

  /**
   * Create investment score card
   */
  private createScoreCard(
    score: PDFGenerationData['investmentScore']
  ): HTMLElement {
    const card = document.createElement('div');
    card.style.backgroundColor = this.getScoreBgColor(score.overall);
    card.style.border = `2px solid ${this.getScoreBorderColor(score.overall)}`;
    card.style.borderRadius = '12px';
    card.style.padding = '20px';
    card.style.marginBottom = '24px';

    const header = document.createElement('div');
    header.style.display = 'flex';
    header.style.justifyContent = 'space-between';
    header.style.alignItems = 'center';
    header.style.marginBottom = '16px';

    const title = document.createElement('h2');
    title.textContent = 'Investment Score';
    title.style.margin = '0';
    title.style.fontSize = '16px';
    title.style.fontWeight = '600';
    title.style.color = '#0f172a';

    const scoreValue = document.createElement('div');
    scoreValue.style.textAlign = 'right';

    const scoreNumber = document.createElement('div');
    scoreNumber.textContent = `${score.overall}/100`;
    scoreNumber.style.fontSize = '32px';
    scoreNumber.style.fontWeight = '700';
    scoreNumber.style.color = this.getScoreTextColor(score.overall);
    scoreNumber.style.margin = '0';

    const recommendation = document.createElement('div');
    recommendation.textContent = score.recommendation
      .replace(/_/g, ' ')
      .toUpperCase();
    recommendation.style.fontSize = '11px';
    recommendation.style.fontWeight = '600';
    recommendation.style.color = this.getScoreTextColor(score.overall);
    recommendation.style.marginTop = '4px';
    recommendation.style.textTransform = 'uppercase';
    recommendation.style.letterSpacing = '0.5px';

    scoreValue.appendChild(scoreNumber);
    scoreValue.appendChild(recommendation);

    header.appendChild(title);
    header.appendChild(scoreValue);
    card.appendChild(header);

    // Breakdown bars
    const breakdown = document.createElement('div');

    const metrics = [
      { label: 'Financial Health', value: score.breakdown.financial },
      { label: 'Market Fit', value: score.breakdown.market },
      { label: 'Team/Profile', value: score.breakdown.team },
      { label: 'Traction', value: score.breakdown.traction },
    ];

    metrics.forEach((metric, idx) => {
      const metricRow = document.createElement('div');
      metricRow.style.display = 'flex';
      metricRow.style.alignItems = 'center';
      metricRow.style.justifyContent = 'space-between';
      metricRow.style.marginBottom = idx < metrics.length - 1 ? '12px' : '0';

      const label = document.createElement('span');
      label.textContent = metric.label;
      label.style.fontSize = '12px';
      label.style.color = '#475569';
      label.style.minWidth = '120px';

      const barContainer = document.createElement('div');
      barContainer.style.flex = '1';
      barContainer.style.height = '6px';
      barContainer.style.backgroundColor = '#e2e8f0';
      barContainer.style.borderRadius = '3px';
      barContainer.style.marginRight = '8px';
      barContainer.style.overflow = 'hidden';

      const bar = document.createElement('div');
      bar.style.height = '100%';
      bar.style.width = `${metric.value}%`;
      bar.style.background = 'linear-gradient(to right, #14b8a6, #0d9488)';
      bar.style.borderRadius = '3px';

      barContainer.appendChild(bar);

      const value = document.createElement('span');
      value.textContent = `${metric.value}%`;
      value.style.fontSize = '12px';
      value.style.fontWeight = '600';
      value.style.color = '#0f172a';
      value.style.minWidth = '32px';
      value.style.textAlign = 'right';

      metricRow.appendChild(label);
      metricRow.appendChild(barContainer);
      metricRow.appendChild(value);
      breakdown.appendChild(metricRow);
    });

    card.appendChild(breakdown);

    // Confidence footer
    const footer = document.createElement('div');
    footer.style.marginTop = '12px';
    footer.style.paddingTop = '12px';
    footer.style.borderTop = `1px solid ${this.getScoreBorderColor(
      score.overall
    )}`;
    footer.style.fontSize = '11px';
    footer.style.color = '#64748b';
    footer.textContent = `Confidence: ${score.confidence}%`;

    card.appendChild(footer);

    return card;
  }

  /**
   * Create market context section
   */
  private createMarketContextSection(marketContext: string): HTMLElement {
    const section = document.createElement('div');
    section.style.backgroundColor = '#f0fdfa';
    section.style.border = '2px solid #99f6e4';
    section.style.borderRadius = '12px';
    section.style.padding = '16px';
    section.style.marginBottom = '24px';

    const title = document.createElement('h3');
    title.textContent = 'Market Context';
    title.style.margin = '0 0 8px 0';
    title.style.fontSize = '14px';
    title.style.fontWeight = '600';
    title.style.color = '#0d4f4a';

    const content = document.createElement('p');
    content.textContent = marketContext;
    content.style.margin = '0';
    content.style.fontSize = '12px';
    content.style.color = '#0d4f4a';
    content.style.lineHeight = '1.6';

    section.appendChild(title);
    section.appendChild(content);

    return section;
  }

  /**
   * Create insights section
   */
  private createInsightsSection(
    insights: Array<{
      title: string;
      description: string;
      type: string;
      severity: 'low' | 'medium' | 'high';
      recommendation: string;
      source?: string;
      confidence?: number;
    }>
  ): HTMLElement {
    const section = document.createElement('div');
    section.style.marginBottom = '24px';

    const title = document.createElement('h2');
    title.textContent = `Insights (${insights.length})`;
    title.style.margin = '0 0 16px 0';
    title.style.fontSize = '16px';
    title.style.fontWeight = '600';
    title.style.color = '#0f172a';

    section.appendChild(title);

    // Sort by severity
    const sorted = [...insights].sort((a, b) => {
      const severityOrder: Record<'high' | 'medium' | 'low', number> = {
        high: 3,
        medium: 2,
        low: 1,
      };
      return severityOrder[b.severity] - severityOrder[a.severity];
    });

    sorted.forEach((insight, index) => {
      const card = this.createInsightCard(insight);
      if (index < sorted.length - 1) {
        card.style.marginBottom = '12px';
      }
      section.appendChild(card);
    });

    return section;
  }

  /**
   * Create individual insight card
   */
  private createInsightCard(insight: {
    title: string;
    description: string;
    type: string;
    severity: 'low' | 'medium' | 'high';
    recommendation: string;
    source?: string;
    confidence?: number;
  }): HTMLElement {
    const card = document.createElement('div');
    const bgColor = this.getInsightBgColor(insight.severity);
    const borderColor = this.getInsightBorderColor(insight.severity);
    const textColor = this.getInsightTextColor(insight.severity);

    card.style.backgroundColor = bgColor;
    card.style.border = `1px solid ${borderColor}`;
    card.style.borderRadius = '8px';
    card.style.padding = '12px';
    card.style.display = 'flex';
    card.style.gap = '12px';

    // Severity indicator
    const indicator = document.createElement('div');
    indicator.style.width = '4px';
    indicator.style.backgroundColor = this.getInsightIndicatorColor(
      insight.severity
    );
    indicator.style.borderRadius = '2px';
    indicator.style.flexShrink = '0';

    // Content
    const content = document.createElement('div');
    content.style.flex = '1';

    const insightTitle = document.createElement('h4');
    insightTitle.textContent = insight.title;
    insightTitle.style.margin = '0 0 4px 0';
    insightTitle.style.fontSize = '12px';
    insightTitle.style.fontWeight = '600';
    insightTitle.style.color = textColor;

    const description = document.createElement('p');
    description.textContent = insight.description;
    description.style.margin = '0 0 6px 0';
    description.style.fontSize = '11px';
    description.style.color = textColor;
    description.style.lineHeight = '1.5';

    const recommendation = document.createElement('p');
    recommendation.textContent = `→ ${insight.recommendation}`;
    recommendation.style.margin = '0';
    recommendation.style.fontSize = '11px';
    recommendation.style.fontWeight = '500';
    recommendation.style.color = textColor;

    content.appendChild(insightTitle);
    content.appendChild(description);
    content.appendChild(recommendation);

    card.appendChild(indicator);
    card.appendChild(content);

    return card;
  }

  /**
   * Color helpers
   */
  private getScoreBgColor(score: number): string {
    if (score >= 75) return '#f0fdf4';
    if (score >= 60) return '#fffbeb';
    if (score >= 40) return '#eff6ff';
    return '#fef2f2';
  }

  private getScoreBorderColor(score: number): string {
    if (score >= 75) return '#86efac';
    if (score >= 60) return '#fcd34d';
    if (score >= 40) return '#93c5fd';
    return '#fca5a5';
  }

  private getScoreTextColor(score: number): string {
    if (score >= 75) return '#166534';
    if (score >= 60) return '#b45309';
    if (score >= 40) return '#1e40af';
    return '#991b1b';
  }

  private getInsightBgColor(severity: string | undefined): string {
    switch (severity) {
      case 'high':
        return '#fef2f2';
      case 'medium':
        return '#fffbeb';
      case 'low':
        return '#eff6ff';
      default:
        return '#f8fafc';
    }
  }

  private getInsightBorderColor(severity: string | undefined): string {
    switch (severity) {
      case 'high':
        return '#fecaca';
      case 'medium':
        return '#fde68a';
      case 'low':
        return '#bfdbfe';
      default:
        return '#e2e8f0';
    }
  }

  private getInsightTextColor(severity: string | undefined): string {
    switch (severity) {
      case 'high':
        return '#7f1d1d';
      case 'medium':
        return '#78350f';
      case 'low':
        return '#1e3a8a';
      default:
        return '#475569';
    }
  }

  private getInsightIndicatorColor(severity: string | undefined): string {
    switch (severity) {
      case 'high':
        return '#dc2626';
      case 'medium':
        return '#f59e0b';
      case 'low':
        return '#3b82f6';
      default:
        return '#6b7280';
    }
  }

  /**
   * Format helpers
   */
  private formatDateForDisplay(date: Date): string {
    return new Intl.DateTimeFormat('en-ZA', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(date);
  }

  private formatDateForFilename(date: Date): string {
    return new Intl.DateTimeFormat('en-ZA', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    })
      .format(date)
      .replace(/\//g, '-');
  }
}
